services:
  - type: web
    name: washingmachine-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_BASE_URL
        fromService:
          type: web
          name: washingmachine-web
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: washingmachine-db
          property: connectionString
      - key: INTERNAL_API_SECRET
        generateValue: true
      - key: ABA_GROUP_ID
        value: -1002522488273
      - key: ABA_BOT_ID
        value: 1148497258
      - key: TELEGRAM_BOT_USERNAME
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ABA_PAY_URL_TEMPLATE
        sync: false
      - key: ADMIN_PANEL_USERNAME
        sync: false
      - key: ADMIN_PANEL_PASSWORD
        sync: false
      - key: SESSION_EXPIRE_MINUTES
        value: 3
      - key: DEFAULT_WASH_DURATION_MINUTES
        value: 30
      - key: MACHINE_OFFLINE_SECONDS
        value: 45

  - type: worker
    name: washingmachine-worker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BACKEND_URL
        fromService:
          type: web
          name: washingmachine-web
          property: url
      - key: DATABASE_URL
        fromDatabase:
          name: washingmachine-db
          property: connectionString
      - key: INTERNAL_API_SECRET
        fromService:
          type: web
          name: washingmachine-web
          envVarKey: INTERNAL_API_SECRET
      - key: ABA_GROUP_ID
        value: -1002522488273
      - key: ABA_BOT_ID
        value: 1148497258
      - key: GROUP_MACHINE_CODE
        value: WM-01
      - key: TG_API_ID
        sync: false
      - key: TG_API_HASH
        sync: false
      - key: TG_STRING_SESSION
        sync: false
      - key: TG_SESSION_NAME
        value: aba_listener

databases:
  - name: washingmachine-db
    plan: free
